[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
nodejs = "24.11.1"
java = "openjdk-25.0.1+8.0.LTS"
hugo = "0.152.2"
deno = "2.5.6"
uv = "0.9.13"
"aqua:cli/cli" = "latest"
"aqua:jdx/usage" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@ccusage/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
"npm:ccusage" = "latest"
"npm:rulesync" = "latest"
"npm:wrangler" = "latest"
