[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[tools]
"aqua:cli/cli" = "latest"
"aqua:jdx/usage" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@ccusage/codex" = "latest"
"npm:@github/copilot" = "latest"
"npm:@openai/codex" = "latest"
"npm:ccusage" = "latest"
"npm:rulesync" = "latest"
"npm:wrangler" = "latest"
